fix responsive
ripio/rcn-loans pull request #687
Opened 2021-05-17 19:31 UTC by martinbobbio

2021-05-17 21:35 UTC, nicolaswww requested changes

2021-05-17 21:35 UTC, nicolaswww commented on src/app/shared/dashboard-list-item/dashboard-list-item.component.html
> +          [matTooltip]="'Accrued interest: ' + paymentProgress"
@martinbobbio check this copy

2021-05-17 21:35 UTC, nicolaswww commented on src/app/shared/dashboard-list-item/dashboard-list-item.component.html
> +      [matTooltip]="'Effective rate: ' + anualRate"
@martinbobbio check this copy

2021-05-17 21:35 UTC, nicolaswww commented on src/app/shared/dashboard-list-item/dashboard-list-item.component.html
> +          <app-redeem-button [loan]="loan" *ngIf="canRedeem" name="Withdraw Collateral">
@martinbobbio the flag canRedeem changes when startRedeem() is called, please add this

2021-05-17 23:21 UTC, martinbobbio commented on src/app/shared/dashboard-list-item/dashboard-list-item.component.html
> +          [matTooltip]="'Accrued interest: ' + paymentProgress"
Removed tooltip and add ToDo

2021-05-17 23:22 UTC, martinbobbio commented on src/app/shared/dashboard-list-item/dashboard-list-item.component.html
> +      [matTooltip]="'Effective rate: ' + anualRate"
Removed tooltip and add ToDo

2021-05-18 14:41 UTC, nicolaswww approved these changes

2021-05-18 14:41 UTC, merged